### ISSUE TITLE
ImportError at launch

### ISSUE THREAD

**Issue by lonfo1** [Hamuko/cum#13]
I managed to install cum, but launching it with any command results in

Traceback (most recent call last):
  File "/usr/local/bin/cum", line 9, in <module>
    load_entry_point('cum==0.2.1', 'console_scripts', 'cum')()
  File "/usr/local/lib/python2.7/dist-packages/click-5.1-py2.7.egg/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click-5.1-py2.7.egg/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click-5.1-py2.7.egg/click/core.py", line 1024, in invoke
    Command.invoke(self, ctx)
  File "/usr/local/lib/python2.7/dist-packages/click-5.1-py2.7.egg/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click-5.1-py2.7.egg/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cum-0.2.1-py2.7.egg/cum/cum.py", line 8, in cli
    from cum import db, output
ImportError: cannot import name db

**Comment by usleep** [comment]
Cum is written in Python 3, if this will help.

**Comment by lonfo1** [comment]
Oh.

Okay, problem solved then.
(By the way, isn't there a way to set a custom directory for downloads?)

**Comment by lonfo1** [comment]
Nevermind, found it.

**Comment by Hamuko** [comment]
I'll add a mention of Python3 in the README file. I could also look if I can enforce Python 3.x in the setup.py file.

**Comment by CounterPillow** [comment]
>(By the way, isn't there a way to set a custom directory for downloads?)

There is in the config file.
