### ISSUE TITLE
Fails to follow new series if it has the same alias of a previously unfollow series.

### ISSUE THREAD

**Issue by MrAmnesiac** [Hamuko/cum#26]
First of all; Thank you for your software, it is life saving. I use it everyday!

Try the following:

- `cum follow https://bato.to/comic/_/comics/happiness-oshimi-shuzo-r14710`
- `cum unfollow happiness-oshimi-shuzo`
- `cum follow https://manga.madokami.com/Manga/H/HA/HAPP/Happiness%20%28OSHIMI%20Shuzo%29`

https://manga.madokami.com/Manga/H/HA/HAPP/Happiness%20%28OSHIMI%20Shuzo%29 would create a new series with the alias "happiness-oshimi-shuzo", however, since that alias has been previously used, it returns an error. There _seems_ to be no way to choose an alias while following, the only possible solution would be manually editing cum.db.

Changing between batoto, madokami and dynastyscans can useful for us, sometimes.

And without further ado, here's the traceback:

```
==> Adding follow for Happiness (OSHIMI Shuzo) (happiness-oshimi-shuzo)
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/cum/scrapers/base.py", line 44, in follow
    s = db.session.query(db.Series).filter_by(url=self.url).one()
  File "/usr/lib/python3.5/site-packages/SQLAlchemy-1.0.12-py3.5-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2699, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/SQLAlchemy-1.0.12-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/lib/python3.5/site-packages/SQLAlchemy-1.0.12-py3.5-linux-x86_64.egg/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: series.alias

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/cum", line 9, in <module>
    load_entry_point('cum==0.5.1', 'console_scripts', 'cum')()
  File "/usr/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/cum/cum.py", line 15, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/cum/cum.py", line 199, in follow
    series.follow()
  File "/usr/lib/python3.5/site-packages/cum/scrapers/base.py", line 48, in follow
    db.session.commit()
  File "/usr/lib/python3.5/site-packages/SQLAlchemy-1.0.12-py3.5-linux-x86_64.egg/sqlalchemy/orm/session.py", line 801, in commit
    self.transaction.commit()
  File "/usr/lib/python3.5/site-packages/SQLAlchemy-1.0.12-py3.5-linux-x86_64.egg/sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File "/usr/lib/python3.5/site-packages/SQLAlchemy-1.0.12-py3.5-linux-x86_64.egg/sqlalchemy/orm/session.py", line 372, in _prepare_impl
    self.session.flush()
  File "/usr/lib/python3.5/site-packages/SQLAlchemy-1.0.12-py3.5-linux-x86_64.egg/sqlalchemy/orm/session.py", line 2019, in flush
    self._flush(objects)
  File "/usr/lib/python3.5/site-packages/SQLAlchemy-1.0.12-py3.5-linux-x86_64.egg/sqlalchemy/orm/session.py", line 2137, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/lib/python3.5/site-packages/SQLAlchemy-1.0.12-py3.5-linux-x86_64.egg/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/lib/python3.5/site-packages/SQLAlchemy-1.0.12-py3.5-linux-x86_64.egg/sqlalchemy/util/compat.py", line 184, in reraise
    raise value
  File "/usr/lib/python3.5/site-packages/SQLAlchemy-1.0.12-py3.5-linux-x86_64.egg/sqlalchemy/orm/session.py", line 2101, in _flush
    flush_context.execute()
  File "/usr/lib/python3.5/site-packages/SQLAlchemy-1.0.12-py3.5-linux-x86_64.egg/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/usr/lib/python3.5/site-packages/SQLAlchemy-1.0.12-py3.5-linux-x86_64.egg/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/usr/lib/python3.5/site-packages/SQLAlchemy-1.0.12-py3.5-linux-x86_64.egg/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "/usr/lib/python3.5/site-packages/SQLAlchemy-1.0.12-py3.5-linux-x86_64.egg/sqlalchemy/orm/persistence.py", line 800, in _emit_insert_statements
    execute(statement, params)
  File "/usr/lib/python3.5/site-packages/SQLAlchemy-1.0.12-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python3.5/site-packages/SQLAlchemy-1.0.12-py3.5-linux-x86_64.egg/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python3.5/site-packages/SQLAlchemy-1.0.12-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python3.5/site-packages/SQLAlchemy-1.0.12-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/lib/python3.5/site-packages/SQLAlchemy-1.0.12-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python3.5/site-packages/SQLAlchemy-1.0.12-py3.5-linux-x86_64.egg/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3.5/site-packages/SQLAlchemy-1.0.12-py3.5-linux-x86_64.egg/sqlalchemy/util/compat.py", line 183, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.5/site-packages/SQLAlchemy-1.0.12-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/lib/python3.5/site-packages/SQLAlchemy-1.0.12-py3.5-linux-x86_64.egg/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: series.alias [SQL: 'INSERT INTO series (name, alias, url, following, directory) VALUES (?, ?, ?, ?, ?)'] [parameters: ('Happiness (OSHIMI Shuzo)', 'happiness-oshimi-shuzo', 'https://manga.madokami.com/Manga/H/HA/HAPP/Happiness%20%28OSHIMI%20Shuzo%29', 1, None)]
```

**Comment by MrAmnesiac** [comment]
Also gonna take the chance and give 2 suggestions for 2 new commands! :laughing: :ok_hand: 

>cum info [alias]

Shows info of a followed series:

ex: `cum info manga-x`
Last update: 25/10/2015  -  c050
directory: ~/Cum/Manga-X
alias: manga-x
link: bato.to/comic/_/comics/manga-x-r2000
downloaded chapters:
01 02 03 04 05 06 07 08 ...

With this ^, you could get rid of the command "alias" and replace it with "edit"
>cum edit [alias] [alias/directory/link] [new alias/new directory/new link]

ex: `cum edit manga-x alias manga-y`

What do you think?

**Comment by Hamuko** [comment]
Sounds pretty solid actually. I'll have a look at fixing the code.

**Comment by Hamuko** [comment]
`cum edit` has been merged to master.
