### ISSUE TITLE
Error following in bato.to

### ISSUE THREAD

**Issue by hanxue** [Hamuko/cum#46]
I have the latest version of `cum`

```
$ cum --version
cum version 0.8 "Miyamo Chio"
```

This happens when I follow a commit on bato.to, with or without the trailing slash in the URL

```
$ cum follow http://bato.to/comic/_/comics/grancrest-senki-r21482/
Traceback (most recent call last):
  File "/usr/local/bin/cum", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/cum/cum.py", line 15, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/cum/cum.py", line 209, in follow
    series = utility.series_by_url(url)
  File "/usr/local/lib/python3.6/site-packages/cum/utility.py", line 71, in series_by_url
    return Series(url)
  File "/usr/local/lib/python3.6/site-packages/cum/scrapers/batoto.py", line 18, in __init__
    self.chapters = self.get_chapters()
  File "/usr/local/lib/python3.6/site-packages/cum/scrapers/batoto.py", line 40, in get_chapters
    name = columns[0].img.next_sibling.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by Hamuko** [comment]
Can you check if the same behavior happens on git master?

```
pip install --upgrade git+https://github.com/Hamuko/cum
```
